server:
  port: 8080

spring:
  application:
    name: template

app:
  api:
    doc:
      version: 1.0
    rest:
      connecttimeout: 3000
      readTimeout: 300


  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:template
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs